gameOn/config/routes.rb
Rails.application.routes.draw do

  get 'user/index'
  root 'user#index'
  resources :users
  get 'users/show'

  get 'game/index'
  resources :games

  get 'game/new'

  get 'games/show'
  resources :games

end

gameOn/app/models/game.rb
class Game < ActiveRecord::Base
end

gameOn/app/models/user.rb
class User < ActiveRecord::Base
end

gameOn/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

gameOn/app/controllers/game_controller.rb
class GameController < ApplicationController
  def create
    @game = Game.find_or_create_by(params[:name])
  end
  def show
    @games = Game.all
  end
  def new
  end

end

gameOn/app/controllers/user_controller.rb
class UserController < ApplicationController
  def create
  end

  def show
    @users = User.all
  end
  def new
  end
end

gameOn/app/helpers/application_helper.rb
module ApplicationHelper
end

gameOn/app/helpers/game_helper.rb
module GameHelper

  #@games.each do |game|
   # game.name
 # end


end

gameOn/app/helpers/user_helper.rb
module UserHelper
end

gameOn/app/views/game/index.html.erb
<h1>)The game page</h1>

<%= link_to 'See all the games', new_game %>

<%= link_to 'Add a game', new_game_path %>

<!-- Get list of games based on prefs-->

gameOn/app/views/game/new_game.html.erb
<h1>Add a game</h1>

<!--name, error if game already exits-->
<%= form_for :game do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>
<h3>Characteristics:</h3>
<p>
  <%= f.label :player_interaction %><br>
  <%= f.text_field :player_interaction, :placeholder => 'Enter true or false'%>
  <!--change to yes or no or use drop down select dot?-->
</p>
<p>
  <%= f.label :bluffing %><br>
  <%= f.text_field :bluffing%>
</p>
<p>
  <%= f.label :quick_setup %><br>
  <%= f.text_field :quick_setup%>
</p>
<p>
  <%= f.label :secret_info %><br>
  <%= f.text_field :secret_info%>
</p>
<p>
  <%= f.label :chance %><br>
  <%= f.text_field :chance%>
</p>
<p>
  <%= f.label :card_based %><br>
  <%= f.text_field :card_based %>
</p>
<p>
  <%= f.label :two_player %><br>
  <%= f.text_field :two_player %>
</p>
<p>
  <%= f.label :theme %><br>
  <%= f.text_field :theme %>
</p>
<p>
  <%= f.label :heavy_reading %><br>
  <%= f.text_field :heavy_reading %>
</p>
<p>
  <%= f.label :kid_friendly %><br>
  <%= f.text_field :kid_friendly %>
</p>
<p>
  <%= f.label :requires_performance %><br>
  <%= f.text_field :requires_performance %>
</p>
<p>
  <%= f.label :randomness_starting_state %><br>
  <%= f.text_field :randomness_starting_state %>
</p>
<p>
  <%= f.label :asymmetric %><br>
  <%= f.text_field :asymmetric %>
</p>
<%= f.submit %>
<% end %>

gameOn/app/views/game/show.html.erb
<!-- does each loop go here or in helper? -->

gameOn/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GameOn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

gameOn/app/views/user/index.html.erb
<h1>Welcome to gameOn</h1>

<!-- if current_user redirect_to game_index_path -->
<h2>Log in</h2>
<%= form_for :user do |f| %>
<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %><br>
  <%= f.text_field :password %>
</p>

<%= f.submit %>
<% end%>

<%= link_to 'Sign Up', new_user_path %>
<!--'Log out'-->
-----------------------------------------------

<%= link_to 'See all gamers', user_path %>

gameOn/app/views/user/new_user.html.erb
<h1>Create an account</h1>

<%= form_for :user do |f| %>
<p>
  <%= f.label :user_name %><br>
  <%= f.text_field :user_name %>
</p>
<p>
  <%= f.label :email %><br>
  <%= f.text_field :email %>
</p>
<p>
  <%= f.label :password %><br>
  <%= f.text_field :password, :placeholder => 'Must be 8 characters long'%> %>
</p>
<h3>Game Preferences:</h3>
<p>
  <%= f.label :player_interaction %><br>
  <%= f.text_field :player_interaction, :placeholder => 'Enter true or false'%>
  <!--change to yes or no or use drop down select dot?-->
</p>
<p>
  <%= f.label :bluffing %><br>
  <%= f.text_field :bluffing%>
</p>
<p>
  <%= f.label :quick_setup %><br>
  <%= f.text_field :quick_setup%>
</p>
<p>
  <%= f.label :secret_info %><br>
  <%= f.text_field :secret_info%>
</p>
<p>
  <%= f.label :chance %><br>
  <%= f.text_field :chance%>
</p>
<p>
  <%= f.label :card_based %><br>
  <%= f.text_field :card_based %>
</p>
<p>
  <%= f.label :two_player %><br>
  <%= f.text_field :two_player %>
</p>
<p>
  <%= f.label :theme %><br>
  <%= f.text_field :theme %>
</p>
<p>
  <%= f.label :heavy_reading %><br>
  <%= f.text_field :heavy_reading %>
</p>
<p>
  <%= f.label :kid_friendly %><br>
  <%= f.text_field :kid_friendly %>
</p>
<p>
  <%= f.label :requires_performance %><br>
  <%= f.text_field :requires_performance %>
</p>
<p>
  <%= f.label :randomness_starting_state %><br>
  <%= f.text_field :randomness_starting_state %>
</p>
<p>
  <%= f.label :asymmetric %><br>
  <%= f.text_field :asymmetric %>
</p>
<%= f.submit %>
<% end %>